### ISSUE TITLE
World no longer loading on mobile devices

### ISSUE THREAD

**Issue by schreiner806** [QuirkyCort/gears#1]
Last time I attempted to use the simulator on an iPad was July 21.  Tried again today and the world won’t appear.

**Comment by QuirkyCort** [comment]
That's probably due to readPixelsAsync. It's a major performance enhancement, but requires WebGL2. Didn't realize earlier that Safari still doesn't support it (...WebGL2 has been supported by other browsers for over 3 years now...).

I've put in a check for WebGL2 support, and reverts back to the older readPixels if WebGL2 is not available. That should fix your problem. Please let me know if it doesn't. I don't have an iPad and can't test it out.

**Comment by schreiner806** [comment]
Thanks for fixing that
